### ISSUE TITLE
i found bug

### ISSUE THREAD

**Issue by carlosrene66** [Azuz396/AG-Website#2]
i cant reload when i use ammo pls fix

also can i help with the website?

**Comment by Azuz396** [comment]
not gonna be fixed

**Comment by Azuz396** [comment]
and no we dont need help k thx

**Comment by Azuz396** [comment]
open pr's if u want kk

**Comment by carlosrene66** [comment]
> and no we dont need help k thx
you will take ages if you keep making useless bots

**Comment by Azuz396** [comment]
> > and no we dont need help k thx
> 
> you will take ages if you keep making useless bots

Ok buddy

**Comment by carlosrene66** [comment]
> > > and no we dont need help k thx
> > 
> > 
> > you will take ages if you keep making useless bots
> 
> Ok buddy

am i wrong doe

**Comment by Azuz396** [comment]
> > > > and no we dont need help k thx
> > > 
> > > 
> > > you will take ages if you keep making useless bots
> > 
> > 
> > Ok buddy
> 
> am i wrong doe

not my fault that azoz doesnt add guns and skins
